import { auth } from '@/lib/firebase';
import { Skeleton } from '@chakra-ui/react';
import { Inter } from 'next/font/google';
import { useAuthState } from 'react-firebase-hooks/auth';
import Dashboard from './dashboard';

import UserForm from './userForm';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [user, loading, error] = useAuthState(auth);
  if (loading) {
    return <Skeleton />;
  }
  if (error) {
    return 'There was an error';
  }
  if (!user) {
    return <UserForm />;
  }

  return <Dashboard />;
}

//   return (
//     <form onSubmit={handleSubmit}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Container>
//         <Center display={'flex'} flexDir={'column'}>
//           <Heading
//             style={{
//               fontFamily: 'sans-serif',
//             }}
//           >
//             Enter your name to start
//           </Heading>

//           <Box>
//             <Input
//               type="text"
//               name=""
//               id=""
//               className="input"
//               placeholder="Name"
//               value={name}
//               onChange={(e) => setName(e.target.value)}
//               required
//             />
//           </Box>

//           <Button colorScheme={'blue'} size="md" type="submit">
//             Start
//           </Button>
//         </Center>
//       </Container>
//     </form>
//   );
// }
