import Board from '@/components/Board';
import { gameSubject } from '@/lib/Game';
import { Center, Container } from '@chakra-ui/layout';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [board, setBoard] = useState([]);

  console.log('board', board);

  useEffect(() => {
    const subscribe = gameSubject.subscribe((game: any) =>
      setBoard(game.board)
    );
    return () => subscribe.unsubscribe();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        minHeight={'100vh'}
        display={'flex'}
        background={'rgb(34, 34, 34)'}
        alignItems={'center'}
        justifyContent={'center'}
      >
        <Center width={'600px'} height={'600px'}>
          <Board board={board}></Board>
        </Center>
      </Container>
    </>
  );
}
